### ISSUE TITLE
Deploy to GitHub actions and check performance

### ISSUE THREAD

**Issue by AshGw** [AshGw/ashgw.io#176]
### New feature description

_

### New feature implementation

````yaml
name: GitHub Pages

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 8 * * *"
jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "21.6.1"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./out
          cname: patrickdesjardins.com
````
